# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '11:95:f7:ab:a3:67:f9:c6:7f:56:e7:a0:15:e6:e0:29'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - '11:95:f7:ab:a3:67:f9:c6:7f:56:e7:a0:15:e6:e0:29'

      - run: echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCT2K3RJXXwZlXMXGHY5PmFpO3Lf8ADoBvS9uHP3fhAbRuP+ZKiZE1dzRHn/3JCu2+/3Tkf4YQa6/CKE3c/M9Tz8kMVLmdc7svD1Jo6VvnVoCufhq9qSx8Cmpj2k/n+rFt/b08iETj9zp+Wmtjzmd4II9Zm4V/S7YYojsjWWd72s8O1PIKdBzT+u/Wg7a2R3u0y7UVsXdboL+GzfDqjayfiumIjkiX24iWFasbwD2CA4KI/mgzstFO0TShSHSocK5i9AlDgM2hx7WLcO+NhsgDGd4LTy7X3KAgDUHXANSPZ0LgXkH6ATQOVDfpEbRHNHPWxljboTkEPHR4nOa8fzbsP >> ~/.ssh/known_hosts

      - run:
          name: upload files to azure
          command: sudo scp -r loftschool-react-task7/* andrey@fms-dev.francecentral.cloudapp.azure.com:/etc/nginx/sites-available/task7

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
